[alias]
test-upstream = "run --features test-harness --bin test-upstream"
coverage = "llvm-cov --workspace --all-targets --features test-harness --lcov --output-path coverage/lcov.info --ignore-filename-regex src/bin/test-upstream.rs$"
coverage-html = "llvm-cov --workspace --all-targets --features test-harness --html --output-dir coverage/html --ignore-filename-regex src/bin/test-upstream.rs$"
